language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
env:
  - CI_JOB=lint_syntax
  - CI_JOB=lint_style
matrix:
  exclude:
    - php: '5.6'
      env: CI_JOB=lint_style
    - php: '7.0'
      env: CI_JOB=lint_style
    - php: '7.1'
      env: CI_JOB=lint_style
script:
  - bash ci/ci.sh --dir ./
